import {
  dbooks_clone,
  et_exit,
  fashion_site,
  food_delivery,
  instagram_clone,
  portfolio_design,
  research,
  tw_stack,
  ui_ux,
  with_computer,
} from "@/assets";

export const PROJECT_LIST = [
  {
    title: "Exit exam platform for MOE",
    description: "Visually impaired  inclusive exam platform",
    imageUrl: et_exit,
    languages: [
      "NextJs",
      "Typescript",
      "MongoDB",
      "Prisma",
      "Tailwindcss",
      "Nodemailer",
      "authjs",
    ],
    previewUrl: "https://et-exit.netlify.app",
    sourceCodeUrl: "https://github.com/onesamket/et-exit",
  },

  {
    title: "Online Food Delivery ",
    description: "Blazing fast online food delivery website ",
    imageUrl: food_delivery,
    languages: [
      "NextJs",
      "Typescript",
      "PostgresSQL",
      "Tailwindcss",
      "Nodemailer",
      "authjs",
      "Prisma",
    ],
    previewUrl: "https://tw-delivery.netlify.app",
    sourceCodeUrl: "https://github.com/onesamket/delivery",
  },
  {
    title: "Pre-configured Js Stacks",
    description: "Start developing application with my stacks",
    imageUrl: tw_stack,
    languages: ["NextJs", "shadcnui", "Typescript"],
    previewUrl: "https://tw-stack.vercel.app",
    sourceCodeUrl: "https://github.com/onesamket/tw-stack",
  },
  {
    title: "Fashion E-commerce website",
    description: "Ethiopia  fashion e-commerce website ",
    imageUrl: fashion_site,
    languages: [
      "NextJs",
      "Zustand",
      "MySQL",
      "Tailwindcss",
      "Nodemailer",
      "Typescript",
      "Prisma",
    ],
    previewUrl: "https://et-fashion.netlify.app",
    sourceCodeUrl: "https://github.com/onesamket/fashion",
  },
  {
    title: "Research  Management System ",
    description: "Efficient research management  platform.",
    imageUrl: research,
    languages: [
      "NextJs",
      "shadcnui",
      "MySQL",
      "Nodemailer",
      "Typescript",
      "Prisma",
    ],
    previewUrl: "https://tw-researcher.netlify.app",
    sourceCodeUrl: "https://github.com/onesamket/researcher",
  },
  {
    title: "Mobile App UI/UX",
    description: "Amazing mobile application UI/UX design",
    imageUrl: ui_ux,
    languages: ["Figma", "icon8"],
    previewUrl: "#",
    sourceCodeUrl: "#",
  },
  {
    title: "dBooks  Clone ",
    description: "Home of Free books to download and read website ",
    imageUrl: dbooks_clone,
    languages: ["Remix", "daisyui"],
    previewUrl: "d-books-clone.vercel.app",
    sourceCodeUrl: "https://github.com/onesamket/dBooks-clone",
  },
  {
    title: "Developer porfolio  website ",
    description: "Amazing developer portfolio website ",
    imageUrl: portfolio_design,
    languages: ["Nextjs", "typescript", "shadcnui", "framer motion", ""],
    previewUrl: "#",
    sourceCodeUrl: "https://github.com/onesamket/onesamket",
  },
  {
    title: "Instagram UI  clone ",
    description: "Instagram clone using react native and nativewind ",
    imageUrl: instagram_clone,
    languages: ["expo", "nativewind", "zustand"],
    previewUrl: "#",
    sourceCodeUrl: "https://github.com/onesamket/instagram-ui-clone",
  },
];
