export const skillsList = [
  {
    label: 'Javascript',
    link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  },
  { label: 'Typescript', link: 'https://www.typescriptlang.org/docs/' },
  { label: 'Tailwindcss', link: 'https://tailwindcss.com/docs' },
  { label: 'Shadcn', link: 'https://ui.shadcn.dev/' },
  { label: 'Nativewind', link: 'https://www.nativewind.dev' },
  { label: 'React', link: 'https://react.dev/' },
  { label: 'Framer Motion', link: 'https://framer.com/motion' },
  { label: 'Next.js', link: 'https://nextjs.org/' },
  {
    label: 'Tanstack Query',
    link: 'https://tanstack.com/query/latest/docs/react/overview',
  },
  {
    label: 'React Native',
    link: 'https://reactnative.dev',
  },
  {
    label: 'Zustand',
    link: 'https://docs.pmnd.rs/zustand/getting-started/introduction',
  },
  { label: 'Remix.run', link: 'https://remix.run' },
  {
    label: 'React query',
    link: 'https://tanstack.com/query/latest/docs/react/overview',
  },
  { label: 'Expo', link: 'https://docs.expo.dev' },
  {
    label: 'Express',
    link: 'https://expressjs.com/en/starter/installing.html',
  },
  { label: 'Bun', link: 'https://bun.sh/docs' },
  { label: 'Socket.io', link: 'https://socket.io/' },
  { label: 'VideoSDK', link: 'https://videosdk.live/' },
  { label: 'Jitsi', link: 'https://jitsi.org/' },
  { label: 'PeerJs', link: 'https://peerjs.com/' },
  { label: 'Prisma', link: 'https://www.prisma.io/docs' },
  { label: 'MySQL', link: 'https://dev.mysql.com/doc/' },
  { label: 'MongoDB', link: 'https://www.mongodb.com/docs/' },
  { label: 'GraphQL', link: 'https://graphql.org/learn/' },
  { label: 'Rest API', link: 'https://restfulapi.net/' },
  { label: 'Supabase', link: 'https://supabase.com/docs' },
  { label: 'Docker', link: 'https://docker.com/docs' },
  { label: 'Git & Github', link: 'https://docs.github.com/en' },
  {
    label: 'More ++',
    link: 'https://github.com/onesamket',
  },
];
