export interface Experience {
  role: string
  company: string
  period: string
  location: string
  technologies: Array<string>
  highlights: Array<string>
}

export const experiences: Array<Experience> = [
  {
    role: 'Frontend Developer',
    company: 'Joveo',
    period: 'Feb 2026 - Present',
    location: 'Remote · Full-time',
    technologies: [
      'React',
      'TypeScript',
      'Tailwind CSS',
      'GraphQL',
      'REST APIs',
    ],
    highlights: [
      'Engineering high-performance, accessible web interfaces and component modules for recruitment marketing platforms.',
      'Refactoring legacy front-end views into reusable design-system components, speeding up feature delivery and reducing code redundancy.',
      'Collaborating with backend and product teams to integrate complex data streams with predictable client-side state and resilient error handling.',
      'Optimizing asset delivery and client bundle sizes to deliver smooth, sub-second page transitions across international user sessions.',
    ],
  },
  {
    role: 'Code Quality & AI Specialist',
    company: 'Revelo',
    period: 'Feb 2026 - Apr 2026',
    location: 'Remote · Contract',
    technologies: [
      'TypeScript',
      'JavaScript',
      'Python',
      'Unit Testing',
      'LLM Benchmarking',
    ],
    highlights: [
      'Audited, evaluated, and benchmarked code generated by Large Language Models across TypeScript, JavaScript, and full-stack environments.',
      'Designed and executed comprehensive test suites, edge-case validations, and algorithmic checks to ensure production correctness.',
      'Delivered detailed technical feedback and scoring rubrics to systematically improve model reliability for real-world software engineering tasks.',
    ],
  },
  {
    role: 'Frontend Developer',
    company: 'Robotech Technology',
    period: 'May 2025 - Feb 2026',
    location: 'Hybrid · Part-time',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Vite', 'REST'],
    highlights: [
      'Developed responsive client portals and management dashboards with clean component hierarchies and intuitive user workflows.',
      'Improved Core Web Vitals and initial page load speed by 35% through dynamic code-splitting and asset optimization.',
      'Built type-safe form validation pipelines and predictable UI states to maximize application stability.',
    ],
  },
  {
    role: 'Full-Stack Developer',
    company: 'Independent Contract & Client Work',
    period: 'Jan 2023 - Feb 2026',
    location: 'Remote · Contract',
    technologies: [
      'React',
      'Next.js',
      'Node.js',
      'WebRTC',
      'PostgreSQL',
      'CI/CD',
    ],
    highlights: [
      'Delivered end-to-end web applications and high-fidelity custom portals for international clients with zero-downtime deployments.',
      'Engineered real-time features including low-latency WebRTC audio/video communication and WebSocket synchronization.',
      'Automated deployment workflows using GitHub Actions and Docker-backed Linux hosting with strict linting and test verification.',
    ],
  },
  {
    role: 'React Native Developer',
    company: 'Prophecius Technologies',
    period: 'Aug 2024 - Feb 2025',
    location: 'Remote · Freelance',
    technologies: [
      'React Native',
      'Expo',
      'TypeScript',
      'Mobile UX',
      'Native APIs',
    ],
    highlights: [
      'Crafted cross-platform mobile features for iOS and Android using React Native and Expo with 60fps animations.',
      'Implemented secure user authentication, local storage caching, and offline-first state synchronization.',
      'Optimized memory usage and mobile rendering cycles to ensure smooth interactions across diverse mobile devices.',
    ],
  },
]
